#!/usr/bin/env bash
# Gate for the ntindle fork: everything must compile, and the packages the fork changes or
# hooks into must pass their tests. Run from the repository root.
set -euo pipefail

go build ./...

fork_packages=(
  ./cmd/server/...
  ./internal/api/...
  ./internal/config/...
  ./internal/registry/...
  ./internal/watcher/...
  ./sdk/api/handlers/...
  ./sdk/cliproxy/...
)

go vet "${fork_packages[@]}"
go test -count=1 "${fork_packages[@]}"

# The image entrypoint and health check are plain shell; catch syntax errors before a build.
sh -n docker/fork/entrypoint.sh
bash -n docker/fork/healthcheck.sh
